### PR TITLE
feat(createDecorator) added a section with createDecorator

### PR DESCRIPTION
**Pull request by m-suchorski**
Added a section about `createDecorator`. If the description (usage, mainly) is too long then I'll change that, just though it's good to provide examples for both types of decorator (with and without params) that can be created with this.

### CODE REVIEW

**Comment by mateuszluczak** [comment]
Looks good!

**Comment by mateuszluczak** [comment]
Can you resolve conflicts with the Constants section that were added `next` branch?

Let's make Utilities above Constants

**Comment by m-suchorski** [comment]
Sure thing, I'll do that in a few minutes.

**Comment by m-suchorski** [comment]
Should be okay now 😄

**Pull request merged**
